# Generated by Django 5.2.1 on 2025-05-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('african_cities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
